//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS {
  using System;


  /// <summary>
  ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
  /// </summary>
  // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
  // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
  // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
  // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0" )]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class gStr {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
    internal gStr() {
    }

    /// <summary>
    ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if( object.ReferenceEquals( resourceMan, null ) ) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "AgOpenGPS.gStr", typeof( gStr ).Assembly );
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Boundary Not Set or No Guidance line set ähnelt.
    /// </summary>
    internal static string gsBoundaryNotSet {
      get {
        return ResourceManager.GetString( "gsBoundaryNotSet", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Boundary Too Small To Create a Headland ähnelt.
    /// </summary>
    internal static string gsBoundaryTooSmall {
      get {
        return ResourceManager.GetString( "gsBoundaryTooSmall", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Click Button Again to Stop ähnelt.
    /// </summary>
    internal static string gsClickButtonAgainToStop {
      get {
        return ResourceManager.GetString( "gsClickButtonAgainToStop", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Close Field ähnelt.
    /// </summary>
    internal static string gsCloseField {
      get {
        return ResourceManager.GetString( "gsCloseField", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Close Field First ähnelt.
    /// </summary>
    internal static string gsCloseFieldFirst {
      get {
        return ResourceManager.GetString( "gsCloseFieldFirst", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Create a Boundary and an ABLine or Curve First ähnelt.
    /// </summary>
    internal static string gsCreateBoundaryFirst {
      get {
        return ResourceManager.GetString( "gsCreateBoundaryFirst", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die ABCurve Not Enabled ähnelt.
    /// </summary>
    internal static string gsCurveNotOn {
      get {
        return ResourceManager.GetString( "gsCurveNotOn", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Turn ABCurve On ähnelt.
    /// </summary>
    internal static string gsCurveTurnOn {
      get {
        return ResourceManager.GetString( "gsCurveTurnOn", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Drawing Has Begun ähnelt.
    /// </summary>
    internal static string gsDrawingHasBegun {
      get {
        return ResourceManager.GetString( "gsDrawingHasBegun", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Ft ähnelt.
    /// </summary>
    internal static string gsFeet {
      get {
        return ResourceManager.GetString( "gsFeet", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Field Is Open ähnelt.
    /// </summary>
    internal static string gsFieldIsOpen {
      get {
        return ResourceManager.GetString( "gsFieldIsOpen", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Field Not Open ähnelt.
    /// </summary>
    internal static string gsFieldNotOpen {
      get {
        return ResourceManager.GetString( "gsFieldNotOpen", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Is your GPS source off? ähnelt.
    /// </summary>
    internal static string gsIsGPSOff {
      get {
        return ResourceManager.GetString( "gsIsGPSOff", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die No GPS ähnelt.
    /// </summary>
    internal static string gsNoGPS {
      get {
        return ResourceManager.GetString( "gsNoGPS", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die No Guidance Lines ähnelt.
    /// </summary>
    internal static string gsNoGuidanceLines {
      get {
        return ResourceManager.GetString( "gsNoGuidanceLines", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die *** No Sentence Data *** ähnelt.
    /// </summary>
    internal static string gsNoSentenceData {
      get {
        return ResourceManager.GetString( "gsNoSentenceData", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
    /// </summary>
    internal static string gsOff {
      get {
        return ResourceManager.GetString( "gsOff", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Program will exit. Please Restart ähnelt.
    /// </summary>
    internal static string gsProgramExitAndRestart {
      get {
        return ResourceManager.GetString( "gsProgramExitAndRestart", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Start New Field ähnelt.
    /// </summary>
    internal static string gsStartNewField {
      get {
        return ResourceManager.GetString( "gsStartNewField", resourceCulture );
      }
    }

    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die Turn on Contour or Make AB Line ähnelt.
    /// </summary>
    internal static string gsTurnOnContourOrABLine {
      get {
        return ResourceManager.GetString( "gsTurnOnContourOrABLine", resourceCulture );
      }
    }
  }
}
